- id: '1738044081884'
  alias: Button Ambiance
  description: ''
  triggers:
  - trigger: time
    at: '19:30:00'
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.office_ambiance
  mode: single
- id: c17468b6-dd40-11ef-8c63-00155d918f67
  alias: Bedside Light Toggle
  description: ''
  triggers:
  - device_id: 82ac3d5614908c19067cae60cf909246
    domain: zha
    type: remote_button_short_press
    subtype: button
    trigger: device
  - device_id: 82ac3d5614908c19067cae60cf909246
    domain: zha
    type: remote_button_short_press
    subtype: button
    trigger: device
  - device_id: 7230294486277129ba36ae06eee4748a
    domain: zha
    type: remote_button_short_press
    subtype: button
    trigger: device
  conditions: []
  actions:
  - action: light.toggle
    metadata: {}
    target:
      entity_id: light.signify_netherlands_b_v_lca005
    data: {}
  mode: single
- id: 18fff798-dd42-11ef-8bc4-00155d918f67
  alias: Activate Office Concentrate
  description: ''
  triggers:
  - trigger: time
    at: 07:15:00
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.office_natural_light_2
  mode: single
- id: '1733544795405'
  alias: Good evening murder
  description: ''
  triggers:
  - trigger: time
    at: '20:15:00'
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.bedroom_murder_2
  mode: single
- id: '1762138711858'
  alias: git pull on commit
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.raypappa_home_assistant_latest_commit
  conditions: []
  actions:
  - action: shell_command.git_pull
    metadata: {}
    data: {}
  mode: single
- id: '1762140408973'
  alias: shower temp delay
  description: ''
  triggers:
  - device_id: 7230294486277129ba36ae06eee4748a
    domain: zha
    type: remote_button_short_press
    subtype: button
    trigger: device
  conditions: []
  actions:
  - action: script.pre_heat_bathroom_2
    metadata: {}
    data: {}
  mode: single
- id: '1762141277519'
  alias: Good Morning wakeup weekday
  description: ''
  triggers:
  - trigger: time
    at: 06:15:00
  conditions:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.new_scene
  - action: scene.turn_on
    metadata: {}
    data:
      transition: 900
    target:
      entity_id: scene.bedside_light_good_morning_post
  - delay:
      hours: 2
      minutes: 0
      seconds: 0
      milliseconds: 0
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      device_id: 17ede8441b0d96619f9255122894377f
  mode: single
- id: '1762649853399'
  alias: Good morning weekenend
  description: ''
  triggers:
  - trigger: time
    at: 08:30:00
  conditions:
  - condition: time
    weekday:
    - sun
    - sat
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.new_scene
  - action: scene.turn_on
    metadata: {}
    data:
      transition: 900
    target:
      entity_id: scene.bedside_light_good_morning_post
  - delay:
      hours: 1
      minutes: 30
      seconds: 0
      milliseconds: 0
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      device_id: 17ede8441b0d96619f9255122894377f
  mode: single
- id: '1763190360771'
  alias: update public dns
  description: ''
  triggers:
  - trigger: time
    at: 05:00:00
  conditions: []
  actions:
  - action: route53.update_records
    metadata: {}
    data: {}
  mode: single
- id: '1763956557659'
  alias: Office get off work
  description: ''
  triggers:
  - trigger: time
    at: '17:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.office_relax_3
  mode: single
- id: '1764409455897'
  alias: Toggle bedroom fan light
  description: ''
  triggers:
  - device_id: f52a8b458b663be3829316c8e1a3ecae
    domain: zha
    type: remote_button_double_press
    subtype: button_1
    trigger: device
  - device_id: 82ac3d5614908c19067cae60cf909246
    domain: zha
    type: remote_button_double_press
    subtype: button
    trigger: device
  conditions: []
  actions: []
  mode: single
- id: '1766370415952'
  alias: Periodic AlwaysOn check
  description: ''
  triggers:
  - trigger: time_pattern
    hours: '*'
    minutes: '15'
    seconds: '0'
  conditions: []
  actions:
  - action: script.turn_on_alwayson_devices
    metadata: {}
    data: {}
  mode: single
- id: '1766653260333'
  alias: Enable good morning weekday
  description: ''
  triggers:
  - trigger: time
    at: '10:00:00'
  conditions: []
  actions:
  - action: automation.turn_on
    metadata: {}
    target:
      entity_id:
      - automation.good_morning_wakeup_weekday
      - automation.good_evening_murder
    data: {}
  mode: single
- id: '1771809131503'
  alias: Stop pre-heating bathroom
  description: ''
  triggers:
  - device_id: 7230294486277129ba36ae06eee4748a
    domain: zha
    type: remote_button_double_press
    subtype: button
    trigger: device
  conditions: []
  actions:
  - action: script.reset_bathroom_temp
    metadata: {}
    data: {}
  mode: single
- id: '1776056887414'
  alias: one time wakeup
  description: ''
  triggers:
  - trigger: time
    at: 05:05:00
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.new_scene
  - action: scene.turn_on
    metadata: {}
    data:
      transition: 900
    target:
      entity_id: scene.bedside_light_good_morning_post
  - delay:
      hours: 2
      minutes: 0
      seconds: 0
      milliseconds: 0
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      device_id: 17ede8441b0d96619f9255122894377f
  - action: automation.turn_off
    metadata: {}
    data:
      stop_actions: false
    target:
      entity_id: automation.one_time_wakeup
  mode: single
- id: '1782702078186'
  alias: Garbage Light Reminder
  description: ''
  triggers:
  - trigger: time
    at: '18:30:00'
    weekday:
    - sun
  conditions: []
  actions:
  - type: turn_on
    device_id: 47b5f45ba4d4bb8c06d091dcdf04c95b
    entity_id: ff7bdde47fc2a25a31cf03735871e9cf
    domain: light
  - delay:
      hours: 4
      minutes: 0
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: 47b5f45ba4d4bb8c06d091dcdf04c95b
    entity_id: ff7bdde47fc2a25a31cf03735871e9cf
    domain: light
  mode: single
- id: '1782702657669'
  alias: Recycling Reminder Light
  description: ''
  triggers:
  - trigger: time
    at: '18:30:00'
    weekday:
    - sun
  conditions:
  - condition: template
    value_template: '{{ now().isocalendar()[1] % 2 == 1 }}  # Odd ISO weeks'
  actions:
  - type: turn_on
    device_id: 47b5f45ba4d4bb8c06d091dcdf04c95b
    entity_id: 61cb69ef64ca94f84f83ae0656b283ca
    domain: light
  - delay:
      hours: 4
      minutes: 0
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: 47b5f45ba4d4bb8c06d091dcdf04c95b
    entity_id: 61cb69ef64ca94f84f83ae0656b283ca
    domain: light
  mode: single
